data_type: 'huggingface'  # Options: 'huggingface', 'parquet', 'dummy'
train_data_path: '/Users/enjalot/code/latent-sae/notebooks/data/test_train'
val_data_path: '/Users/enjalot/code/latent-sae/notebooks/data/test_train'
embedding_column: 'embedding'  # Column name containing the pre-computed embeddings
learning_rate: 0.0001
weight_decay: 0.01
l1_lambda: 0.00001
auxk_lambda: 0.000001
batch_size: 16
accumulation_steps: 8
k: 128
auxk: 32
expansion_factor: 16
dead_steps_threshold: 1000
epochs: 1